cargo-features = [ "strip" ]


[workspace]
members = [
    "boot",
    "kernel",
    "crates/*",
    "apps/*",
    "hal",
    "executive/*",
    "security/*"
]

[profile.release]
strip = true

[profile.dev]
strip = true
