[package]
name = "boot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.12.0", features = ["exts"] }
uefi-services = "0.9.0"
log = { version = "0.4.14", default-features = false }
xmas-elf = "0.8.0"
bks = { path = "../crates/bks" }