[package]
name = "esys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0" # Will never be dropped
enumtastic = { path = "../enumtastic" }