# ----###---##+- Esque.toml -+##---###----
# Edit your build of the Esque kernel
# Attention: To edit the CI-Specific config, please use
# the CI.toml file

## ATTENTION - WHILE THIS WORKS ON MY LOCAL MACHINE, IT STILL CALLS THE OLD FILE ON THE CI
[package]
arch = "x86_64"
version = "0.0.1"
name = "Winter Wonderland"
initramfs = "default"
documentation = true
cargo-flags = [ "" ]
mode = "debug"
should-run = false # Should the project be run every time *any* commmand is invoked? (Not recommended)
never-run = false # Should any --run or ./y.py run be ignored?
out-image-path = "build/esque-m"
minimal-toolchain = true

[kernel]
features = [ ""]
cargo-flags = [ "mirror" ] # Also mirrors the global flags
mode = "mirror" # Mirrors global mode

[boot]
features = [ "" ]
cargo-flags = [ "mirror" ]
mode = "mirror"

[modules]
no-modules = false
modules = []

[qemu]
memlim = "512M"
enable-kvm = true
cpu = "qemu64" # Not needed if enable-kvm is on
logfile = "qemu.log"
should-log = true # Should log to file?
smp = 1 # Cores
machine = "q35"
qemu-opts = [] # Additional arguments